variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

cache:
  paths:
    - .m2/repository

.install: &install
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS -pl !talkadvisor-infra/talkadvisor-infra-acceptance-tests install'

.acceptance-tests: &acceptance-tests
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS -pl talkadvisor-infra/talkadvisor-infra-acceptance-tests verify'

acceptance-tests:
  <<: *acceptance-tests
  image: maven:3.3.9-jdk-8

# Verify merge requests using JDK8
install:jdk8:
  <<: *install
  image: maven:3.3.9-jdk-8
